/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.VisualizarRpt;

/**
 *
 * @author Henrique
 */
public class dlgFiltroRpt extends javax.swing.JDialog {

    MaskFormatter mfData;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private int rptInt;

    /**
     * Creates new form dlgFiltroRpt
     */
    public dlgFiltroRpt(int rpt) {
        initComponents();
        buttonGroup1.add(rdbAberto);
        buttonGroup1.add(rdbEntregue);
        buttonGroup1.add(rdbCancelado);
        try {
            pnlStatus.setVisible(false);
            rptInt = rpt;
            if (rptInt == 2) {
                pnlStatus.setVisible(true);
            }
            mfData = new MaskFormatter("##/##/####");
            mfData.setValueContainsLiteralCharacters(true);
            mfData.setPlaceholderCharacter('_');
            mfData.setValueClass(String.class);
            DefaultFormatterFactory ddfData = new DefaultFormatterFactory(mfData);
            txtDataInicial.setFormatterFactory(ddfData);
            txtDataFinal.setFormatterFactory(ddfData);

            Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (screen.width - this.getWidth()) / 2;
            int y = (screen.height - this.getHeight()) / 2;

            setBounds(x, y, this.getWidth(), this.getHeight());
            setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        btnGerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlStatus = new javax.swing.JPanel();
        rdbAberto = new javax.swing.JRadioButton();
        rdbEntregue = new javax.swing.JRadioButton();
        rdbCancelado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("De");

        jLabel2.setText("a");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        rdbAberto.setText("Aberto");

        rdbEntregue.setText("Entregue");

        rdbCancelado.setText("Cancelado");

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rdbAberto)
                .addGap(35, 35, 35)
                .addComponent(rdbEntregue)
                .addGap(28, 28, 28)
                .addComponent(rdbCancelado)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAberto)
                    .addComponent(rdbCancelado)
                    .addComponent(rdbEntregue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        try {
            Map parametros = new HashMap();
            String par1 = "", par2 = "", parStatus = "", titulo = "", arquivo = "";
            switch (rptInt) {
                case 1:
                    arquivo = "rpt_previsaoEntrega.jasper";
                    titulo = "Previsão de Entrega";
                    par1 = "DataEntregaInicial";
                    par2 = "DataEntregaFinal";
                    break;
                case 2:
                    arquivo = "rptRelacaoPedidos.jasper";
                    titulo = "Relação de Pedidos";
                    par1 = "dtVendaInicial";
                    par2 = "dtVendaFinal";
                    parStatus = "stp";
                    int stp = 0;
                    if (rdbAberto.isSelected()) {
                        stp = 0;
                    }
                    if (rdbEntregue.isSelected()) {
                        stp = 1;
                    }
                    if (rdbCancelado.isSelected()) {
                        stp = 2;
                    }
                    parametros.put(parStatus, stp);
                    break;
                case 3:
                    arquivo = "rptPrevisaoRecebimento.jasper";
                    titulo = "Previsão de Recebimento";
                    par1 = "dtVctoInicial";
                    par2 = "dtVctoFinal";
                    break;
                case 4:
                    arquivo = "rptRelacaoRecebimento.jasper";
                    titulo = "Relação de Recebimento";
                    par1 = "dtPgtoInicial";
                    par2 = "dtPgtoFinal";
                    break;
            }
                parametros.put(par1, sdf.parse(txtDataInicial.getText()));
                parametros.put(par2, sdf.parse(txtDataFinal.getText()));

            VisualizarRpt.geraRelatorio(arquivo, parametros, titulo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + ex.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    public static void showDlgFiltro(int rpt) {
        dlgFiltroRpt filtroRpt = new dlgFiltroRpt(rpt);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JRadioButton rdbAberto;
    private javax.swing.JRadioButton rdbCancelado;
    private javax.swing.JRadioButton rdbEntregue;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
