package view;

import javax.swing.JDialog;

/**
 *
 * @author Henrique
 */
public class mdiMenu extends javax.swing.JFrame {

    public mdiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenuItem();
        menuComercial = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        manuFinanceiro = new javax.swing.JMenu();
        menuDuplicatas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuRptPrevisaoEntrega = new javax.swing.JMenuItem();
        menuRptRelacaoPedidos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        rptPrevisaoRecebimento = new javax.swing.JMenuItem();
        rptRelacaoRecebimento = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuEmpresa = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setState(6);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        menuClientes.setMnemonic('o');
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        fileMenu.add(menuClientes);

        menuProdutos.setMnemonic('s');
        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        fileMenu.add(menuProdutos);

        menuBar.add(fileMenu);

        menuComercial.setMnemonic('e');
        menuComercial.setText("Comercial");

        menuPedidos.setText("Pedidos");
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        menuComercial.add(menuPedidos);

        jMenuItem1.setText("Orçamentos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuComercial.add(jMenuItem1);

        menuBar.add(menuComercial);

        manuFinanceiro.setMnemonic('h');
        manuFinanceiro.setText("Financeiro");

        menuDuplicatas.setText("Duplicatas");
        menuDuplicatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDuplicatasActionPerformed(evt);
            }
        });
        manuFinanceiro.add(menuDuplicatas);

        menuBar.add(manuFinanceiro);

        jMenu5.setText("Relatótios");

        jMenu6.setText("Comercial");

        menuRptPrevisaoEntrega.setText("Previsão de Entrega");
        menuRptPrevisaoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRptPrevisaoEntregaActionPerformed(evt);
            }
        });
        jMenu6.add(menuRptPrevisaoEntrega);

        menuRptRelacaoPedidos.setText("Relação de Pedidos");
        menuRptRelacaoPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRptRelacaoPedidosActionPerformed(evt);
            }
        });
        jMenu6.add(menuRptRelacaoPedidos);

        jMenu5.add(jMenu6);

        jMenu7.setText("Financeiro");

        rptPrevisaoRecebimento.setText("Previsão de Recebimento");
        rptPrevisaoRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptPrevisaoRecebimentoActionPerformed(evt);
            }
        });
        jMenu7.add(rptPrevisaoRecebimento);

        rptRelacaoRecebimento.setText("Relação de Recebimento");
        rptRelacaoRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptRelacaoRecebimentoActionPerformed(evt);
            }
        });
        jMenu7.add(rptRelacaoRecebimento);

        jMenu5.add(jMenu7);

        menuBar.add(jMenu5);

        jMenu8.setText("Configurações");
        jMenu8.setToolTipText("Em breve...");
        jMenu8.setEnabled(false);

        menuEmpresa.setText("Empres");
        menuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresaActionPerformed(evt);
            }
        });
        jMenu8.add(menuEmpresa);

        menuBar.add(jMenu8);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        frmClientes frmClientes1 = new frmClientes();
        desktopPane.add(frmClientes1);
        frmClientes1.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        frmProdutos frmProdutos1 = new frmProdutos();
        desktopPane.add(frmProdutos1);
        frmProdutos1.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuRptPrevisaoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRptPrevisaoEntregaActionPerformed
        dlgFiltroRpt.showDlgFiltro(1);
    }//GEN-LAST:event_menuRptPrevisaoEntregaActionPerformed

    private void menuRptRelacaoPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRptRelacaoPedidosActionPerformed
        dlgFiltroRpt.showDlgFiltro(2);
    }//GEN-LAST:event_menuRptRelacaoPedidosActionPerformed

    private void rptPrevisaoRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptPrevisaoRecebimentoActionPerformed
        dlgFiltroRpt.showDlgFiltro(3);
    }//GEN-LAST:event_rptPrevisaoRecebimentoActionPerformed

    private void rptRelacaoRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptRelacaoRecebimentoActionPerformed
        dlgFiltroRpt.showDlgFiltro(4);
    }//GEN-LAST:event_rptRelacaoRecebimentoActionPerformed

    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        frmPedidos frmPedidos1 = new frmPedidos();
        desktopPane.add(frmPedidos1);
        frmPedidos1.setVisible(true);
    }//GEN-LAST:event_menuPedidosActionPerformed

    private void menuDuplicatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDuplicatasActionPerformed
        frmDuplicatas frmDuplicatas1 = new frmDuplicatas();
        desktopPane.add(frmDuplicatas1);
        frmDuplicatas1.setVisible(true);
    }//GEN-LAST:event_menuDuplicatasActionPerformed
    /*  TODO Ver sobre tela de configuracoes de emrpesa*/
    private void menuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresaActionPerformed
        frmConfiguracoes frmConfig1 = new frmConfiguracoes();
        desktopPane.add(frmConfig1);
        frmConfig1.setVisible(true);
    }//GEN-LAST:event_menuEmpresaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmOrcamento frmOrcamento1 = new frmOrcamento();
        desktopPane.add(frmOrcamento1);
        frmOrcamento1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu manuFinanceiro;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenu menuComercial;
    private javax.swing.JMenuItem menuDuplicatas;
    private javax.swing.JMenuItem menuEmpresa;
    private javax.swing.JMenuItem menuPedidos;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuRptPrevisaoEntrega;
    private javax.swing.JMenuItem menuRptRelacaoPedidos;
    private javax.swing.JMenuItem rptPrevisaoRecebimento;
    private javax.swing.JMenuItem rptRelacaoRecebimento;
    // End of variables declaration//GEN-END:variables

}
